// frontend-react/src/components/EditMotoForm.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { getMotoById, updateMoto } from '../services/motoService';
import '../styles/EditMotoForm.css';

const EditMotoForm: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [moto, setMoto] = useState<any>(null);

  useEffect(() => {
    const fetchMoto = async () => {
      const fetchedMoto = await getMotoById(id!);
      setMoto(fetchedMoto);
    };
    fetchMoto();
  }, [id]);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    try {
      await updateMoto(id!, moto);
      alert('Moto mise à jour avec succès');
      navigate('/motos');
    } catch (error) {
      alert('Erreur lors de la mise à jour');
    }
  };

  if (!moto) return <p>Chargement...</p>;

  return (
    <form className="edit-moto-form" onSubmit={handleSubmit}>
      <h2>Modifier la Moto</h2>
      <div className="form-group">
        <label>Modèle :</label>
        <input type="text" value={moto.modele} onChange={(e) => setMoto({ ...moto, modele: e.target.value })} />
      </div>
      <div className="form-group">
        <label>Kilométrage :</label>
        <input type="number" value={moto.kilometrage} onChange={(e) => setMoto({ ...moto, kilometrage: parseInt(e.target.value) })} />
      </div>
      <div className="form-group">
        <label>Date du Dernier Entretien :</label>
        <input type="date" value={moto.dateDernierEntretien} onChange={(e) => setMoto({ ...moto, dateDernierEntretien: e.target.value })} />
      </div>
      <button type="submit">Modifier</button>
    </form>
  );
};

export default EditMotoForm;

// frontend-angular/src/app/edit-moto-form/edit-moto-form.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { MotoService, Moto } from '../services/moto.service';

@Component({
  selector: 'app-edit-moto-form',
  templateUrl: './edit-moto-form.component.html',
  styleUrls: ['./edit-moto-form.component.css']
})
export class EditMotoFormComponent implements OnInit {
  moto: Moto = {
    modele: '',
    kilometrage: 0,
    dateDernierEntretien: ''
  };
  id: string | null = null;

  constructor(
    private route: ActivatedRoute,
    private motoService: MotoService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.id = this.route.snapshot.paramMap.get('id');
    if (this.id) {
      this.motoService.getMotoById(this.id).subscribe(
        (data) => this.moto = data,
        (error) => console.error(error)
      );
    }
  }

  handleSubmit(): void {
    if (this.id) {
      this.motoService.updateMoto(this.id, this.moto).subscribe(
        () => {
          alert('Moto mise à jour avec succès');
          this.router.navigate(['/motos']);
        },
        (error) => console.error('Erreur :', error)
      );
    }
  }
}

<p>edit-moto-form works!</p>

<form (ngSubmit)="handleSubmit()">
    <label>Modèle :</label>
    <input
      type="text"
      [(ngModel)]="moto.modele"
      name="modele"
      required
    />
  
    <label>Kilométrage :</label>
    <input
      type="number"
      [(ngModel)]="moto.kilometrage"
      name="kilometrage"
      required
    />
  
    <label>Date du dernier entretien :</label>
    <input
      type="date"
      [(ngModel)]="moto.dateDernierEntretien"
      name="dateDernierEntretien"
      required
    />
  
    <button type="submit">Mettre à jour la moto</button>
  </form>
