// frontend-react/src/components/MotoDetail.tsx
import React, { useEffect, useState } from 'react';
import axios from 'axios';
import { useParams } from 'react-router-dom';

interface Moto {
  id: string;
  modele: string;
  kilometrage: number;
  dateDernierEntretien: string;
}

const MotoDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [moto, setMoto] = useState<Moto | null>(null);

  useEffect(() => {
    axios.get(`${process.env.REACT_APP_API_URL}/motos/${id}`)
      .then(response => setMoto(response.data))
      .catch(error => console.error(error));
  }, [id]);

  if (!moto) return <div>Loading...</div>;

  return (
    <div>
      <h2>{moto.modele}</h2>
      <p>Kilométrage : {moto.kilometrage} km</p>
      <p>Date du dernier entretien : {moto.dateDernierEntretien}</p>
    </div>
  );
};

export default MotoDetail;

// frontend-angular/src/app/moto-detail/moto-detail.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { MotoService, Moto } from '../services/moto.service';

@Component({
  selector: 'app-moto-detail',
  templateUrl: './moto-detail.component.html',
  styleUrls: ['./moto-detail.component.css']
})
export class MotoDetailComponent implements OnInit {
  moto: Moto | null = null;

  constructor(
    private route: ActivatedRoute,
    private motoService: MotoService
  ) { }

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id');
    if (id) {
      this.motoService.getMotoById(id).subscribe(
        (data) => this.moto = data,
        (error) => console.error(error)
      );
    }
  }
}

<p>moto-detail works!</p>
<div *ngIf="moto">
    <h2>{{ moto.modele }}</h2>
    <p>Kilométrage : {{ moto.kilometrage }} km</p>
    <p>Date du dernier entretien : {{ moto.dateDernierEntretien }}</p>
  </div>
  <div *ngIf="!moto">
    Loading...
  </div>
