// frontend-react/src/components/AddMotoForm.tsx
import React, { useState } from 'react';
import { createMoto } from '../services/motoService';
import '../styles/AddMotoForm.css';

const AddMotoForm: React.FC = () => {
  const [modele, setModele] = useState('');
  const [kilometrage, setKilometrage] = useState(0);
  const [dateDernierEntretien, setDateDernierEntretien] = useState('');

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    try {
      await createMoto({ modele, kilometrage, dateDernierEntretien: new Date(dateDernierEntretien) });
      alert('Moto ajoutée avec succès !');
    } catch (error) {
      alert('Erreur lors de l\'ajout de la moto');
    }
  };

  return (
    <form className="add-moto-form" onSubmit={handleSubmit}>
      <h2>Ajouter une Moto</h2>
      <div className="form-group">
        <label>Modèle :</label>
        <input type="text" value={modele} onChange={(e) => setModele(e.target.value)} />
      </div>
      <div className="form-group">
        <label>Kilométrage :</label>
        <input type="number" value={kilometrage} onChange={(e) => setKilometrage(parseInt(e.target.value))} />
      </div>
      <div className="form-group">
        <label>Date du Dernier Entretien :</label>
        <input type="date" value={dateDernierEntretien} onChange={(e) => setDateDernierEntretien(e.target.value)} />
      </div>
      <button type="submit">Ajouter Moto</button>
    </form>
  );
};

export default AddMotoForm;

// frontend-angular/src/app/add-moto-form/add-moto-form.component.ts
import { Component } from '@angular/core';
import { MotoService, Moto } from '../services/moto.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-add-moto-form',
  templateUrl: './add-moto-form.component.html',
  styleUrls: ['./add-moto-form.component.css']
})
export class AddMotoFormComponent {
  moto: Moto = {
    modele: '',
    kilometrage: 0,
    dateDernierEntretien: ''
  };

  constructor(private motoService: MotoService, private router: Router) { }

  handleSubmit(): void {
    this.motoService.addMoto(this.moto).subscribe(
      () => {
        alert('Moto ajoutée avec succès');
        this.router.navigate(['/motos']);
      },
      (error) => console.error('Erreur :', error)
    );
  }
}

<p>add-moto-form works!</p>

<form (ngSubmit)="handleSubmit()">
    <label>Modèle :</label>
    <input
      type="text"
      [(ngModel)]="moto.modele"
      name="modele"
      required
    />
  
    <label>Kilométrage :</label>
    <input
      type="number"
      [(ngModel)]="moto.kilometrage"
      name="kilometrage"
      required
    />
  
    <label>Date du dernier entretien :</label>
    <input
      type="date"
      [(ngModel)]="moto.dateDernierEntretien"
      name="dateDernierEntretien"
      required
    />
  
    <button type="submit">Ajouter la moto</button>
  </form>
